### ISSUE TITLE
Rename About.js to Brand.js

### ISSUE THREAD

**Issue by JameelJiwani** [JameelJiwani/PopUp-react#1]
Pm asked to change the nav item to say "Brands" instead of "About Us." It would be nice to change the code to reflect this

**Comment by rahul-s-bhatt** [comment]
Hey, could you assign this to me?

**Comment by JameelJiwani** [comment]
Sure thing! Let me know if you have any questions 😄

**Comment by rahul-s-bhatt** [comment]
Hey just one question, whether you want to change the files and variables related to **about us** be changed to **brands** (with s) as well?
Or just a simple visual change i.e in the navigation item?

**Comment by JameelJiwani** [comment]
Create question! Both need to be changed.

Originally, this section was designed to be an "About" section but now it's a page for prospect brands to learn more about the company. The navigation item was already changed (see most recent commit) but the `*.js` files should be renamed to reflect this

**Comment by rahul-s-bhatt** [comment]
ERROR: Permission to JameelJiwani/PopUp-react.git denied to rahulbhatt1899.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Kindly assign the task.

**Comment by JameelJiwani** [comment]
Can you provide more detail on what you are trying to do? You cannot push directly to master, you must create a new branch and open a pull request

**Comment by rahulbhatt1899** [comment]
![image](https://user-images.githubusercontent.com/35606353/93800572-6895e200-fc5e-11ea-8e13-597101c2df43.png)
Yeah I did make a separate branch, but tried git push, don't know why am I getting error.
Sorry, this is my first pull request.

**Comment by JameelJiwani** [comment]
Try running `git remote set-url origin https://rahulbhatt1899@github.com/JameelJiwani/PopUp-react.git` then `git push origin branch_name`

**Comment by rahul-s-bhatt** [comment]
I m a total nub at this, it was a fault at my end. I apologize for that. I did open a pull request, check.
